### ISSUE TITLE
DOM access using Abmash

### ISSUE THREAD

**Issue by nobal** [alp82/abmash#2]
Hi All, 

I understand that Abmash is built for visual attributes and visible text. I liked this but I also want to get access to the full DOM tree so that I can utilize both the visual and the DOM level features. Is there a way to get the DOM tree of the document  from Abmash? I tried to use getParent () / getSiblings method of the HtmlElement class but it doesn't work ...

Thanks

**Comment by alp82** [comment]
The usual workflow with Abmash is selecting elements by utilizing different query methods. There is mostly no need to fetch the whole DOM tree.

`getParent()` will select the parent element of the currently selected `HtmlElement` and `getSiblings()` selects all other elements on the same level.

You can use `getTextWithSource()` on an `HtmlElement` to fetch its content including all HTML tags (the method name is not very catchy i guess?). If you do that for the `<html>` tag, you have a String representation of the whole document and can do whatever you want. Example:

```
HtmlElement html = browser.query(select('html')).findFirst(); // select the html element
HtmlElement body = browser.query(select('body')).findFirst(); // or the body element
String htmlContent = html.getTextWithSource();
String bodyContent = body.getTextWithSource();
```

The question is, why would you want to do that? Maybe i misunderstood your question though.

**Comment by nobal** [comment]
Thank you for your suggestions. I selected a html element and tried to get its source but no luck. Looks getTextWithSource() method has bugs. I below show the sample html file, the code and the results. Check this out: 

## test.html

&lt;html&gt;
&lt;head&gt;&lt;title&gt;Hello&lt;/title&gt;&lt;/head&gt;
&lt;body&gt;
&lt;form&gt;
&lt;span&gt;
&nbsp; &lt;span&gt; Name: 
&nbsp; &nbsp;&nbsp;&nbsp; &lt;span&gt;(full name)&lt;/span&gt;
&nbsp; &lt;/span&gt;
&nbsp; &lt;input type = "text" name="userName"/&gt; 
&lt;/span&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;

## The code: 

HtmlElement he = browser.query(typable()).find().first();
HtmlElement parent=he.getParent();
System.out.println("Parent:"+ parent.toString()+"--&gt;"+parent.getText());
System.out.println("He: "+he.getTextWithSource());
HtmlElements siblings = he.getSiblings();
int j=0;
for(HtmlElement s: siblings){
&nbsp;&nbsp;&nbsp; System.out.println(++j+". sib--&gt; text:'"+s.getText()+"'; src:'"+s.getTextWithSource()+"',
toString:'"+s.toString()+"'");
}

## The Result: 

Parent:&lt;span&gt;Name: (full name)&lt;/span&gt;--&gt;Name: (full name)
He: 
1. sib--&gt; text:'Name: (full name)'; src:'null', toString:'&lt;span&gt;Name: (full name)&lt;/span&gt;'

You can see that the getTextWithSource() method is not giving the thing it should...&nbsp; Moreover, there is no method that gives me the children of a given HtmlElement. Do you have any comments on this ?

**Comment by alp82** [comment]
I will look into this issue, thanks for your input.

**Comment by alp82** [comment]
There was indeed a bug that caused `getTextWithSource()` to return `null`. I fixed that and pushed the new version.

Also, i added a `getChildren()` method for `HtmlElement`.

**Comment by nobal** [comment]
It works now, thanks. Also thanks for the getChildren() function.
