### ISSUE TITLE
xpath and selector predicates are not working

### ISSUE THREAD

**Issue by anilreddy** [alp82/abmash#5]
Here is the code i am using

``` java
HtmlElement element = browser.query(select("input=[id^='Email']")).findFirst();
        element.type("testing342");

        browser.type("password", "tester4all");
        browser.click("sign in");
```

when am executing i am getting

``` java
java.lang.NullPointerException
```

and this warning popup message:
![image](https://cloud.githubusercontent.com/assets/3746781/2936045/903dccca-d841-11e3-8572-c2095ab4d6ef.png)

**Comment by alp82** [comment]
The problem are the single quotes for `'Email'`. Currently it seems that there is no escaping for this case.

You can easily fix it by omitting the single quotes or by escaping them manually.

First solution:

```
select("input=[id^=Email]")
```

Second solution:

```
select("input=[id^=\'Email\']")
```

I would prefer the first one.

**Comment by anilreddy** [comment]
@alp82 Thanks it worked..I like abmash and way it locate the objects. But I am seeing some issues and error handling is not properly implemented. Any way I like it. When will you release stable jar?
